# Libraries

```{r load-libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
library(ggplot2)
library(here)
library(readr)
```

## 2.1 Dataset Overview

```{r load-data}
access_healthcare <- read.csv("access-to-health-care_national_zaf.csv")
maternal_mortality <- read.csv( "maternal-mortality_national_zaf.csv")
immunization <- read.csv( "immunization_national_zaf.csv")
child_mortality <- read.csv ("child-mortality-rates_national_zaf.csv")

access_healthcare <- access_healthcare[-1, ]
child_mortality <- child_mortality[-1, ]
immunization <- immunization[-1, ]
maternal_mortality <- maternal_mortality[-1, ]

```

#Chnages data types

```{r}
#Changing Data types

#Convert value to numeric         
access_healthcare$Value <- as.numeric(access_healthcare$Value)
child_mortality$Value <- as.numeric(child_mortality$Value)
immunization$Value <- as.numeric(immunization$Value)
maternal_mortality$Value <- as.numeric(maternal_mortality$Value)

#Convert Precision to numeric         
access_healthcare$Precision  <- as.numeric(access_healthcare$Precision )
child_mortality$Precision  <- as.numeric(child_mortality$Precision )
immunization$Precision  <- as.numeric(immunization$Precision )
maternal_mortality$Precision  <- as.numeric(maternal_mortality$Precision )

#Convert CharacteristicId  to numeric         
access_healthcare$CharacteristicId <- as.character(as.numeric(access_healthcare$CharacteristicId))
child_mortality$CharacteristicId <- as.character(as.numeric(child_mortality$CharacteristicId))
immunization$CharacteristicId <- as.character(as.numeric(immunization$CharacteristicId))
maternal_mortality$CharacteristicId <- as.character(as.numeric(maternal_mortality$CharacteristicId))

# Convert SurveyYear to numeric for plots
access_healthcare$SurveyYear <- as.numeric(access_healthcare$SurveyYear)
child_mortality$SurveyYear <- as.numeric(child_mortality$SurveyYear)
immunization$SurveyYear <- as.numeric(immunization$SurveyYear)
maternal_mortality$SurveyYear <- as.numeric(maternal_mortality$SurveyYear)

# Dropping Column RegionalId no values

access_healthcare$RegionId <- NULL
child_mortality$RegionId <- NULL
immunization$RegionId <- NULL
maternal_mortality$RegionId <- NULL

# Dropping Column RegionalId suplicate values
access_healthcare$SurveyYearLabel <- NULL
child_mortality$SurveyYearLabel<- NULL
immunization$SurveyYearLabel <- NULL
maternal_mortality$SurveyYearLabel <- NULL

# Dropping Column levelRank no values
access_healthcare$LevelRank <- NULL
child_mortality$LevelRank<- NULL
immunization$LevelRank <- NULL
maternal_mortality$LevelRank <- NULL
```

#FIlling missing values
```{r}

child_mortality$ByVariableLabel[child_mortality$ByVariableLabel == "" | is.na(child_mortality$ByVariableLabel)] <- "Unknown"
maternal_mortality$ByVariableLabel[maternal_mortality$ByVariableLabel == "" | is.na(maternal_mortality$ByVariableLabel)] <- "Unknown"
```

#Structure of datasets
```{r}
str(access_healthcare)
str(child_mortality)
str(immunization)
str(maternal_mortality)
```
#Opens up view
```{r}
view(access_healthcare)
view(maternal_mortality)
view(immunization)
view(child_mortality)

```
#Sum of verious data

```{r data-quality}
print('summary of Health care value')
summary(access_healthcare$Value)
print('summary of Child Mortality value')
summary(child_mortality$Value)
print('summary of immunization value')
summary(immunization$Value)
print('summary of  maternal mortality value')
summary(maternal_mortality$Value)

print('Missing Values')
sum(is.na(access_healthcare))
sum(is.na(child_mortality))
sum(is.na(immunization))
sum(is.na(maternal_mortality))

print('Duplicate values')
sum(duplicated(access_healthcare))
sum(duplicated(child_mortality)) 
sum(duplicated(immunization)) 
sum(duplicated(maternal_mortality)) 

```
#Visuals of data

```{r e-analysis}

# Plot child mortality over time
ggplot(child_mortality, aes(x = SurveyYear, y = as.numeric(Value), color = Indicator)) +
  geom_line() +
  labs(title = "Child Mortality Trends in South Africa", x = "Year", y = "Mortality Rate")

# Line chart of BCG vaccination over time
ggplot(filter(immunization, Indicator == "BCG vaccination received"),
       aes(x = SurveyYear, y = Value)) +
  geom_line() +
  geom_point() +
  labs(title = "BCG Vaccination Over Time in South Africa",
       x = "Year", y = "Coverage (%)")

#Access to Health Care - Value Distribution
ggplot(access_healthcare, aes(x = Value)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  labs(title = "Access to Health Care - Value Distribution", x = "Value", y = "Count") +
  theme_minimal()


```

